export type UserT = {
  approved: boolean;
  blocked: boolean;
  email: string;
  firstName: string;
  id: number;
  lastName: string;
  role: string;
  usage?: string;
  createdAt?: string;
  emailIsVerified?: boolean;
  emailVerificationToken?: string;
  passwordResetToken?: string;
  updatedAt?: string;
  notifyOnNewRingVersion?: boolean;
  notifyOnConnectionRequest?: boolean;
  notifyOnConnectionResponse?: boolean;
  notifyOnNewNotebook?: boolean;
  notifyOnSharedNotebook?: boolean;
  notifyOnTeamChange?: boolean;
  notifyOnTeamNotebookDelete?: boolean;
};
