module.exports =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InNhdHlybnBsYXRmb3JtQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJUZXN0aW5nIiwiYmxvY2tlZCI6ZmFsc2UsImFwcHJvdmVkIjp0cnVlfSwiaWF0IjoxNjk4MDczMjQ5LCJleHAiOjE2OTgxNTk2NDl9.KZWpyhf0lOEiSQ-mDwFoH03AVj2_82Mj-xd8Ornqi9s";
