export const courtCase = {
  "@context": {
    case: "http://release.niem.gov/niem/domains/jxdm/7.2/#Case",
    cases: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case", "@container": "@list" },
    entityType: "rdf:type",
    caseDocketId: { "@id": "http://release.niem.gov/niem/niem-core/5.0/CaseDocketID" },
    caseCivil: "http://schemas.scales-okn.org/rdf/scales#CaseCivil",
    caseInitiatingAttorney: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseInitiatingAttorney",
    caseInitiatingParty: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseInitiatingParty",
    caseRespondentParty: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseRespondentParty",
    caseDefenseAttorney: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseDefenseAttorney",
    caseDefendantParty: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseDefendantParty",
    caseProsecutingAttorney: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseProsecutingAttorney",
    caseCriminal: "http://schemas.scales-okn.org/rdf/scales#CaseCriminal",
    caseCourt: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseCourt",
    caseCharge: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseCharge",
    chargeSentence: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeSentence",
    caseJudge: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseJudge",
    caseGeneralCategory: "http://release.niem.gov/niem/niem-core/5.0/CaseGeneralCategoryText",
    jurisdiction: "http://release.niem.gov/niem/niem-core/5.0/JurisdictionText",
    charge: "http://release.niem.gov/niem/domains/jxdm/7.2/#Charge",
    charges: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Charge", "@container": "@list" },
    judge: "http://release.niem.gov/niem/domains/jxdm/7.2/#Judge",
    court: "http://release.niem.gov/niem/domains/jxdm/7.2/#Court",
    caseStatus: "http://release.niem.gov/niem/niem-core/5.0/StatusDescriptionText",
    filingDate: "http://release.niem.gov/niem/niem-core/5.0/StartDate",
    filingDateStart: "http://release.niem.gov/niem/niem-core/5.0/StartDate",
    filingDateEnd: "http://release.niem.gov/niem/niem-core/5.0/EndDate",
    natureSuit: "http://release.niem.gov/niem/niem-core/5.0/CaseSubCategoryText",
    cause: "http://release.niem.gov/niem/niem-core/5.0/StatuteKeywordText",
    chargeDescription: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeText",
    chargeStatus: "http://release.niem.gov/niem/niem-core/5.0/StatusDescriptionText",
    chargeType: "http://schemas.scales-okn.org/rdf/scales#hasChargeType",
    chargeSequenceId: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeSequenceID",
    terminatingDate: "http://release.niem.gov/niem/niem-core/5.0/EndDate",
    ontologyLabel: "http://schemas.scales-okn.org/rdf/scales#hasOntologyLabel",
    disposition: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeDisposition",
    sentence: "http://release.niem.gov/niem/domains/jxdm/7.2/#Sentence",
    sentenceSubject: "http://release.niem.gov/niem/domains/jxdm/7.2/#SentenceSubject",
    sentenceFineAmount: "http://release.niem.gov/niem/domains/jxdm/7.2/#SentenceFineAmount",
    sentenceImposedText: "http://release.niem.gov/niem/domains/jxdm/7.2/#SentenceImposedText",
    personFullName: "http://release.niem.gov/niem/niem-core/5.0/PersonFullName",
    personRace: "http://release.niem.gov/niem/niem-core/5.0/PersonRaceText",
    personSex: "http://release.niem.gov/niem/niem-core/5.0/PersonSexText",
    courtName: "http://release.niem.gov/niem/domains/jxdm/7.2/#CourtName",
    isInCircuit: "http://schemas.scales-okn.org/rdf/scales#isInCircuit",
    judicialOfficialCategory: "http://release.niem.gov/niem/domains/jxdm/7.2/#JudicialOfficialCategoryText",
    commissionDate: "http://schemas.scales-okn.org/rdf/scales#hasCommissionDate",
    appointedByParty: "http://schemas.scales-okn.org/rdf/scales#appointedByParty",
    location: "http://release.niem.gov/niem/niem-core/5.0/Location",
    registerOfActions: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterOfActions",
    registerAction: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterAction",
    registerActionDate: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterActionDate",
    registerActionDescription: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterActionDescriptionText",
    judgeReference: "http://schemas.scales-okn.org/rdf/scales#hasJudgeReference",
    judgeAttribution: "http://schemas.scales-okn.org/rdf/scales#hasIfpJudgeAttribution",
    referenceToOtherEntry: "http://schemas.scales-okn.org/rdf/scales#hasReferenceToOtherEntry",
    administrativeId: "http://release.niem.gov/niem/niem-core/5.0/AdministrativeID",
    highestOffenseLevelOpening: "http://schemas.scales-okn.org/rdf/scales#hasHighestOffenseLevelOpening",
    highestOffenseLevelTerminated: "http://schemas.scales-okn.org/rdf/scales#hasHighestOffenseLevelTerminated",
    partyReferenceExtraInfo: "http://schemas.scales-okn.org/rdf/scales#hasPartyReferenceInExtraInfo",
    caseOfficialRole: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseOfficialRoleText",
    participantRoleCategory: "http://release.niem.gov/niem/domains/jxdm/7.2/#ParticipantRoleCategoryText",
    first: { "@id": "http://www.w3.org/ns/sparql-service-description#limit", "@type": "xsd:integer" },
    offset: { "@id": "http://www.w3.org/ns/sparql-service-description#offset", "@type": "xsd:integer" },
    totalCount: { "@id": "http://www.w3.org/ns/sparql-service-description#totalResults", "@type": "xsd:integer" },
    sortBy: "http://www.w3.org/ns/sparql-service-description#orderBy",
    sortDirection: "http://www.w3.org/ns/sparql-service-description#orderDirection",
    docketTable: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterOfActions",
    nodes: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case", "@container": "@list" }
  },
  "@type": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case",
};
