export const courtCase = {
  "@context": {
    case: "http://release.niem.gov/niem/domains/jxdm/7.2/#Case",
    searchCases: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case", "@container": "@list" },
    cases: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case", "@container": "@list" },
    entityType: "rdf:type",
    caseDocketId: { "@id": "http://release.niem.gov/niem/niem-core/5.0/CaseDocketID" },
    caseCivil: "http://schemas.scales-okn.org/rdf/scales#CaseCivil",
    caseInitiatingAttorney: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseInitiatingAttorney",
    caseInitiatingParty: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseInitiatingParty",
    caseDefenseAttorney: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseDefenseAttorney",
    caseCriminal: "http://schemas.scales-okn.org/rdf/scales#CaseCriminal",
    caseCourt: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseCourt",
    caseCharge: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseCharge",
    chargeSentence: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeSentence",
    caseJudge: "http://release.niem.gov/niem/domains/jxdm/7.2/#CaseJudge",
    caseGeneralCategory: "http://release.niem.gov/niem/niem-core/5.0/CaseGeneralCategoryText",
    jurisdiction: "http://release.niem.gov/niem/niem-core/5.0/JurisdictionText",
    charge: "http://release.niem.gov/niem/domains/jxdm/7.2/#Charge",
    charges: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Charge", "@container": "@list" },
    judge: "http://release.niem.gov/niem/domains/jxdm/7.2/#Judge",
    caseStatus: "http://release.niem.gov/niem/niem-core/5.0/StatusDescriptionText",
    filingDate: "http://release.niem.gov/niem/niem-core/5.0/StartDate",
    filingDateStart: "http://release.niem.gov/niem/niem-core/5.0/StartDate",
    filingDateEnd: "http://release.niem.gov/niem/niem-core/5.0/EndDate",
    natureSuit: "http://release.niem.gov/niem/niem-core/5.0/CaseSubCategoryText",
    cause: "http://release.niem.gov/niem/domains/jxdm/7.2/#StatuteKeywordText",
    chargeStatus: "http://release.niem.gov/niem/niem-core/5.0/StatusDescriptionText",
    chargeType: "http://schemas.scales-okn.org/rdf/scales#hasChargeType",
    terminatingDate: "http://release.niem.gov/niem/niem-core/5.0/EndDate",
    ontologlyLabel: "http://schemas.scales-okn.org/rdf/scales#hasOntologlyLabel",
    disposition: "http://release.niem.gov/niem/domains/jxdm/7.2/#ChargeDisposition",
    first: { "@id": "http://www.w3.org/ns/sparql-service-description#limit", "@type": "xsd:integer" },
    offset: { "@id": "http://www.w3.org/ns/sparql-service-description#offset", "@type": "xsd:integer" },
    totalCount: { "@id": "http://www.w3.org/ns/sparql-service-description#totalResults", "@type": "xsd:integer" },
    sortBy: "http://www.w3.org/ns/sparql-service-description#orderBy",
    sortDirection: "http://www.w3.org/ns/sparql-service-description#orderDirection",
    docketTable: "http://release.niem.gov/niem/domains/jxdm/7.2/#RegisterOfActions",
    nodes: { "@id": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case", "@container": "@list" }
  },
  "@type": "http://release.niem.gov/niem/domains/jxdm/7.2/#Case",
};
